# Generated by Django 4.2.11 on 2026-07-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_order_number',
            new_name='purchase_order_numbers',
        ),
    ]
