# Generated by Django 4.2.11 on 2026-07-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_purchase_order_number_purchase_purchase_order_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_order_numbers',
            new_name='purchase_order_number',
        ),
    ]
