# Generated by Django 4.2.11 on 2026-06-16 22:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('inventory', '0003_purchase_business_purchase_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='discount',
            new_name='purchase_discount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='reference_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
