# Generated by Django 4.2.11 on 2026-07-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_discount_purchase_purchase_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='brand',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='maximum_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='qr_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='track_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('box', 'Box'), ('pack', 'Pack'), ('kg', 'Kilogram'), ('g', 'Gram'), ('ltr', 'Litre'), ('ml', 'Millilitre'), ('carton', 'Carton'), ('bag', 'Bag'), ('roll', 'Roll')], default='pcs', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
