# Generated by Django 4.2.11 on 2026-07-27 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_goodsreceipt_purchaseorder_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code_type', models.CharField(choices=[('barcode', 'Barcode (CODE128)'), ('qrcode', 'QR Code')], default='barcode', max_length=10)),
                ('width_mm', models.PositiveIntegerField(default=40)),
                ('height_mm', models.PositiveIntegerField(default=30)),
                ('columns', models.PositiveIntegerField(default=3, help_text='Labels per row on the print sheet')),
                ('gap_mm', models.PositiveIntegerField(default=2, help_text='Gap between labels, in mm')),
                ('show_business_name', models.BooleanField(default=False)),
                ('show_product_name', models.BooleanField(default=True)),
                ('show_price', models.BooleanField(default=True)),
                ('show_sku', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_templates', to='business.business')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LabelPrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_print_logs', to='business.business')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_print_logs', to='inventory.inventory')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.labeltemplate')),
            ],
            options={
                'ordering': ['-printed_at'],
            },
        ),
    ]
