# Generated by Django 4.2.11 on 2026-07-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0005_inventory_brand_inventory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product_image',
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category'),
        ),
    ]
