# Generated by Django 4.2.11 on 2026-07-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventory_product_image_inventory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='image',
            new_name='product_image',
        ),
    ]
