# Generated by Django 4.2.11 on 2026-07-22 22:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_rename_image_inventory_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening Stock'), ('RESTOCK', 'Restock'), ('SALE', 'Sale'), ('DAMAGE', 'Damage'), ('ADJUSTMENT', 'Adjustment'), ('RETURN_IN', 'Customer Return'), ('RETURN_OUT', 'Supplier Return'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('before_quantity', models.PositiveIntegerField(default=0)),
                ('after_quantity', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='business.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
