# Generated by Django 4.2.11 on 2026-07-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventorymovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorystockhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory Restock', 'verbose_name_plural': 'Inventory Restocks'},
        ),
        migrations.RenameField(
            model_name='inventorystockhistory',
            old_name='performed_by',
            new_name='received_by',
        ),
        migrations.AddField(
            model_name='inventorystockhistory',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='inventorystockhistory',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventorystockhistory',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorystockhistory',
            name='reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inventorystockhistory',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventorystockhistory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restocks', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='inventorystockhistory',
            name='warehouse',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
