# Generated by Django 4.2.11 on 2026-07-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventorystockhistory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorystockhistory',
            old_name='quantity_changed',
            new_name='quantity',
        ),
    ]
