# Generated by Django 4.2.11 on 2026-07-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_quantity_changed_inventorystockhistory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening Stock'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Sales Return'), ('supplier_return', 'Supplier Return'), ('restock', 'Restock'), ('adjustment', 'Stock Adjustment'), ('damage', 'Damaged'), ('expired', 'Expired'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('production', 'Production')], max_length=20),
        ),
    ]
