# Generated by Django 4.2.11 on 2026-07-25 07:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0002_alter_business_owner'),
        ('inventory', '0011_alter_inventorymovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystockhistory',
            name='action_type',
            field=models.CharField(choices=[('restock', 'Restock'), ('sale', 'Sale Deduction'), ('adjustment', 'Manual Adjustment'), ('damaged', 'Damaged'), ('returned', 'Returned'), ('transfer', 'Transfer'), ('expired', 'Expired / Disposed')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=60)),
                ('quantity', models.PositiveIntegerField()),
                ('initial_quantity', models.PositiveIntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(db_index=True)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed')], default='active', max_length=20)),
                ('disposed_quantity', models.PositiveIntegerField(default=0)),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('disposal_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_batches', to='business.business')),
                ('disposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.inventory')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_batches', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Product Batch',
                'verbose_name_plural': 'Product Batches',
                'ordering': ['expiry_date'],
                'unique_together': {('business', 'batch_number')},
            },
        ),
    ]
