# Generated by Django 4.2.11 on 2026-07-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventorystockhistory_action_type_productbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_created', to='inventory.purchase'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
