# Generated by Django 4.2.11 on 2026-07-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Proforma', 'Pro-forma'), ('Partially Refunded', 'Partially Refunded'), ('Refunded', 'Refunded')], default='Completed', max_length=20),
        ),
    ]
